# Site settings
title       : Regina Sánchez´s Blog
description : Presonal Blog

# Serving
baseurl     : "https://regisanchez.github.io"
url         : "/blog/"

# Social settings
github_url  : https://github.com/RegiSanchez
